/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.5
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QLCDNumber>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QListWidget>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *tabAdm;
    QWidget *tab_7;
    QLabel *LBienve;
    QLabel *LCodAdm;
    QLabel *LDijite;
    QLabel *LInfo;
    QLineEdit *TCodigo_3;
    QPushButton *BIngresar_3;
    QWidget *tab_8;
    QLabel *LInsertar;
    QPushButton *BPasillo;
    QPushButton *BProducto;
    QPushButton *BMarca;
    QLabel *LTipo;
    QPushButton *BinsertarPas;
    QLabel *LNombre;
    QLabel *LCodPas;
    QLineEdit *TNombre;
    QLineEdit *TCodigo_4;
    QLabel *LPasillo;
    QComboBox *CBPasillosI;
    QPushButton *BInsertarProd;
    QLabel *LProducto;
    QComboBox *CBProdutos;
    QPushButton *BInsertarMarca;
    QPushButton *pushButton;
    QLabel *LNombreM;
    QLineEdit *TNombreM;
    QLabel *LCodMar;
    QLineEdit *TCodigoM;
    QLabel *LPasilloM;
    QLabel *LCantidad;
    QSpinBox *SCant;
    QLabel *LPrecio;
    QLineEdit *TPrecio;
    QLabel *LCanasta;
    QRadioButton *RBS;
    QRadioButton *RBN;
    QComboBox *CBPasillosIM;
    QPushButton *BVolver3;
    QPushButton *BVolver2;
    QPushButton *BVolver1;
    QWidget *Modificar;
    QPushButton *BModPrecio;
    QLabel *LModificar;
    QPushButton *BModImp;
    QPushButton *BModCan;
    QLabel *LPasMod;
    QLabel *LProdMod;
    QLabel *LMarMod;
    QComboBox *CBPasMod;
    QComboBox *CBProdMod;
    QComboBox *CBMarMod;
    QPushButton *BModi;
    QLabel *LMod;
    QLineEdit *TPrecioMod;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *BModiImp;
    QPushButton *BModiCan;
    QPushButton *BModVol;
    QPushButton *BModVol_2;
    QWidget *tab_9;
    QLabel *LConsultar;
    QLabel *LTipoCon;
    QComboBox *CBTipoCon;
    QPushButton *BBuscarPrecioCon;
    QPushButton *BBuscarOtraCon;
    QLCDNumber *LCDPrecioCon;
    QPushButton *BPrecioCon;
    QPushButton *BImpCon;
    QPushButton *BCanCon;
    QPushButton *BBuscarProdCon;
    QPushButton *BBuscarPasilloCon;
    QLabel *LColonIma;
    QLabel *porcentaje;
    QLabel *confirmacion_2;
    QLabel *confirmacion_3;
    QLabel *confirmacion_4;
    QWidget *tab_11;
    QLabel *label;
    QLabel *LPasEl;
    QLabel *LMarEl;
    QLabel *LProdEl;
    QPushButton *BElimarPas;
    QPushButton *BPasilloEl;
    QPushButton *BProdEl;
    QPushButton *BMarcaEl;
    QComboBox *CBPasEl;
    QComboBox *CBProdEl;
    QComboBox *CBMarEl;
    QPushButton *BEliminaProd;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *BEliminarMarca;
    QPushButton *BClieEl;
    QLabel *LCED;
    QLineEdit *TCedEl;
    QPushButton *BBusEl;
    QPushButton *BSel;
    QPushButton *BActCB;
    QPushButton *BActProd;
    QPushButton *BActMarProd;
    QListWidget *LQClientes;
    QPushButton *BVolver;
    QPushButton *BVolver_2;
    QPushButton *BVolver_3;
    QPushButton *BVolver_4;
    QWidget *tab_12;
    QPushButton *BGondolas;
    QPushButton *BInven;
    QLabel *LVeri;
    QListWidget *LQGong;
    QPushButton *BAgregar;
    QLabel *LCantGon;
    QPushButton *BVolverGon;
    QSpinBox *SGon;
    QListWidget *LQInv;
    QPushButton *BVolverInv;
    QPushButton *BAgregarInv;
    QSpinBox *sInv;
    QWidget *tab;
    QComboBox *CBRPas1;
    QComboBox *CBRPas2;
    QComboBox *CBRPro1;
    QComboBox *CBRPas3;
    QComboBox *CBRPas4;
    QComboBox *CBRPro2;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QPushButton *pushButton_6;
    QPushButton *BBRPas4;
    QPushButton *BBRPas3;
    QPushButton *BBRPas1;
    QPushButton *BBRPas2;
    QPushButton *BBRPro2;
    QPushButton *BBRPro1;
    QWidget *tab_13;
    QPushButton *BFacturar;
    QLabel *LOtros;
    QPushButton *pushButton_7;
    QPushButton *pushButton_8;
    QPushButton *pushButton_9;
    QPushButton *pushButton_10;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->setEnabled(true);
        MainWindow->resize(634, 347);
        MainWindow->setAnimated(true);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        tabAdm = new QTabWidget(centralwidget);
        tabAdm->setObjectName(QString::fromUtf8("tabAdm"));
        tabAdm->setGeometry(QRect(0, 0, 641, 311));
        tab_7 = new QWidget();
        tab_7->setObjectName(QString::fromUtf8("tab_7"));
        LBienve = new QLabel(tab_7);
        LBienve->setObjectName(QString::fromUtf8("LBienve"));
        LBienve->setGeometry(QRect(230, 10, 171, 21));
        LCodAdm = new QLabel(tab_7);
        LCodAdm->setObjectName(QString::fromUtf8("LCodAdm"));
        LCodAdm->setGeometry(QRect(150, 110, 151, 31));
        LDijite = new QLabel(tab_7);
        LDijite->setObjectName(QString::fromUtf8("LDijite"));
        LDijite->setGeometry(QRect(220, 50, 191, 21));
        LInfo = new QLabel(tab_7);
        LInfo->setObjectName(QString::fromUtf8("LInfo"));
        LInfo->setGeometry(QRect(180, 80, 271, 101));
        TCodigo_3 = new QLineEdit(tab_7);
        TCodigo_3->setObjectName(QString::fromUtf8("TCodigo_3"));
        TCodigo_3->setGeometry(QRect(330, 110, 141, 22));
        BIngresar_3 = new QPushButton(tab_7);
        BIngresar_3->setObjectName(QString::fromUtf8("BIngresar_3"));
        BIngresar_3->setGeometry(QRect(260, 180, 93, 28));
        tabAdm->addTab(tab_7, QString());
        tab_8 = new QWidget();
        tab_8->setObjectName(QString::fromUtf8("tab_8"));
        LInsertar = new QLabel(tab_8);
        LInsertar->setObjectName(QString::fromUtf8("LInsertar"));
        LInsertar->setGeometry(QRect(190, 0, 261, 51));
        BPasillo = new QPushButton(tab_8);
        BPasillo->setObjectName(QString::fromUtf8("BPasillo"));
        BPasillo->setGeometry(QRect(200, 60, 221, 31));
        BProducto = new QPushButton(tab_8);
        BProducto->setObjectName(QString::fromUtf8("BProducto"));
        BProducto->setGeometry(QRect(200, 130, 221, 31));
        BMarca = new QPushButton(tab_8);
        BMarca->setObjectName(QString::fromUtf8("BMarca"));
        BMarca->setGeometry(QRect(200, 210, 221, 31));
        LTipo = new QLabel(tab_8);
        LTipo->setObjectName(QString::fromUtf8("LTipo"));
        LTipo->setGeometry(QRect(280, 20, 101, 21));
        BinsertarPas = new QPushButton(tab_8);
        BinsertarPas->setObjectName(QString::fromUtf8("BinsertarPas"));
        BinsertarPas->setGeometry(QRect(190, 160, 131, 31));
        LNombre = new QLabel(tab_8);
        LNombre->setObjectName(QString::fromUtf8("LNombre"));
        LNombre->setGeometry(QRect(150, 60, 55, 16));
        LCodPas = new QLabel(tab_8);
        LCodPas->setObjectName(QString::fromUtf8("LCodPas"));
        LCodPas->setGeometry(QRect(150, 110, 55, 16));
        TNombre = new QLineEdit(tab_8);
        TNombre->setObjectName(QString::fromUtf8("TNombre"));
        TNombre->setGeometry(QRect(250, 60, 171, 22));
        TCodigo_4 = new QLineEdit(tab_8);
        TCodigo_4->setObjectName(QString::fromUtf8("TCodigo_4"));
        TCodigo_4->setGeometry(QRect(250, 110, 171, 22));
        LPasillo = new QLabel(tab_8);
        LPasillo->setObjectName(QString::fromUtf8("LPasillo"));
        LPasillo->setGeometry(QRect(150, 160, 55, 16));
        CBPasillosI = new QComboBox(tab_8);
        CBPasillosI->setObjectName(QString::fromUtf8("CBPasillosI"));
        CBPasillosI->setGeometry(QRect(250, 160, 171, 22));
        BInsertarProd = new QPushButton(tab_8);
        BInsertarProd->setObjectName(QString::fromUtf8("BInsertarProd"));
        BInsertarProd->setGeometry(QRect(190, 210, 131, 31));
        LProducto = new QLabel(tab_8);
        LProducto->setObjectName(QString::fromUtf8("LProducto"));
        LProducto->setGeometry(QRect(100, 180, 55, 16));
        CBProdutos = new QComboBox(tab_8);
        CBProdutos->setObjectName(QString::fromUtf8("CBProdutos"));
        CBProdutos->setGeometry(QRect(160, 180, 171, 22));
        BInsertarMarca = new QPushButton(tab_8);
        BInsertarMarca->setObjectName(QString::fromUtf8("BInsertarMarca"));
        BInsertarMarca->setGeometry(QRect(190, 220, 131, 31));
        pushButton = new QPushButton(tab_8);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(330, 180, 21, 21));
        LNombreM = new QLabel(tab_8);
        LNombreM->setObjectName(QString::fromUtf8("LNombreM"));
        LNombreM->setGeometry(QRect(100, 60, 55, 16));
        TNombreM = new QLineEdit(tab_8);
        TNombreM->setObjectName(QString::fromUtf8("TNombreM"));
        TNombreM->setGeometry(QRect(160, 50, 171, 22));
        LCodMar = new QLabel(tab_8);
        LCodMar->setObjectName(QString::fromUtf8("LCodMar"));
        LCodMar->setGeometry(QRect(100, 100, 55, 16));
        TCodigoM = new QLineEdit(tab_8);
        TCodigoM->setObjectName(QString::fromUtf8("TCodigoM"));
        TCodigoM->setGeometry(QRect(160, 100, 171, 22));
        LPasilloM = new QLabel(tab_8);
        LPasilloM->setObjectName(QString::fromUtf8("LPasilloM"));
        LPasilloM->setGeometry(QRect(100, 140, 55, 16));
        LCantidad = new QLabel(tab_8);
        LCantidad->setObjectName(QString::fromUtf8("LCantidad"));
        LCantidad->setGeometry(QRect(380, 90, 55, 16));
        SCant = new QSpinBox(tab_8);
        SCant->setObjectName(QString::fromUtf8("SCant"));
        SCant->setGeometry(QRect(450, 90, 131, 22));
        LPrecio = new QLabel(tab_8);
        LPrecio->setObjectName(QString::fromUtf8("LPrecio"));
        LPrecio->setGeometry(QRect(380, 140, 55, 16));
        TPrecio = new QLineEdit(tab_8);
        TPrecio->setObjectName(QString::fromUtf8("TPrecio"));
        TPrecio->setGeometry(QRect(450, 140, 131, 22));
        LCanasta = new QLabel(tab_8);
        LCanasta->setObjectName(QString::fromUtf8("LCanasta"));
        LCanasta->setGeometry(QRect(380, 190, 55, 16));
        RBS = new QRadioButton(tab_8);
        RBS->setObjectName(QString::fromUtf8("RBS"));
        RBS->setGeometry(QRect(460, 190, 51, 20));
        RBN = new QRadioButton(tab_8);
        RBN->setObjectName(QString::fromUtf8("RBN"));
        RBN->setGeometry(QRect(520, 190, 51, 20));
        CBPasillosIM = new QComboBox(tab_8);
        CBPasillosIM->setObjectName(QString::fromUtf8("CBPasillosIM"));
        CBPasillosIM->setGeometry(QRect(160, 140, 171, 22));
        BVolver3 = new QPushButton(tab_8);
        BVolver3->setObjectName(QString::fromUtf8("BVolver3"));
        BVolver3->setGeometry(QRect(340, 220, 131, 31));
        BVolver2 = new QPushButton(tab_8);
        BVolver2->setObjectName(QString::fromUtf8("BVolver2"));
        BVolver2->setGeometry(QRect(340, 210, 131, 31));
        BVolver1 = new QPushButton(tab_8);
        BVolver1->setObjectName(QString::fromUtf8("BVolver1"));
        BVolver1->setGeometry(QRect(340, 160, 131, 31));
        tabAdm->addTab(tab_8, QString());
        Modificar = new QWidget();
        Modificar->setObjectName(QString::fromUtf8("Modificar"));
        BModPrecio = new QPushButton(Modificar);
        BModPrecio->setObjectName(QString::fromUtf8("BModPrecio"));
        BModPrecio->setGeometry(QRect(190, 60, 241, 31));
        LModificar = new QLabel(Modificar);
        LModificar->setObjectName(QString::fromUtf8("LModificar"));
        LModificar->setGeometry(QRect(90, 20, 451, 21));
        BModImp = new QPushButton(Modificar);
        BModImp->setObjectName(QString::fromUtf8("BModImp"));
        BModImp->setGeometry(QRect(190, 130, 241, 31));
        BModCan = new QPushButton(Modificar);
        BModCan->setObjectName(QString::fromUtf8("BModCan"));
        BModCan->setGeometry(QRect(190, 200, 241, 31));
        LPasMod = new QLabel(Modificar);
        LPasMod->setObjectName(QString::fromUtf8("LPasMod"));
        LPasMod->setGeometry(QRect(140, 80, 55, 16));
        LProdMod = new QLabel(Modificar);
        LProdMod->setObjectName(QString::fromUtf8("LProdMod"));
        LProdMod->setGeometry(QRect(140, 120, 55, 16));
        LMarMod = new QLabel(Modificar);
        LMarMod->setObjectName(QString::fromUtf8("LMarMod"));
        LMarMod->setGeometry(QRect(140, 160, 55, 16));
        CBPasMod = new QComboBox(Modificar);
        CBPasMod->setObjectName(QString::fromUtf8("CBPasMod"));
        CBPasMod->setGeometry(QRect(240, 70, 191, 21));
        CBProdMod = new QComboBox(Modificar);
        CBProdMod->setObjectName(QString::fromUtf8("CBProdMod"));
        CBProdMod->setGeometry(QRect(240, 110, 191, 22));
        CBMarMod = new QComboBox(Modificar);
        CBMarMod->setObjectName(QString::fromUtf8("CBMarMod"));
        CBMarMod->setGeometry(QRect(240, 150, 191, 22));
        BModi = new QPushButton(Modificar);
        BModi->setObjectName(QString::fromUtf8("BModi"));
        BModi->setGeometry(QRect(220, 230, 93, 28));
        LMod = new QLabel(Modificar);
        LMod->setObjectName(QString::fromUtf8("LMod"));
        LMod->setGeometry(QRect(140, 200, 55, 16));
        TPrecioMod = new QLineEdit(Modificar);
        TPrecioMod->setObjectName(QString::fromUtf8("TPrecioMod"));
        TPrecioMod->setGeometry(QRect(240, 190, 191, 22));
        pushButton_2 = new QPushButton(Modificar);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(430, 150, 20, 20));
        pushButton_3 = new QPushButton(Modificar);
        pushButton_3->setObjectName(QString::fromUtf8("pushButton_3"));
        pushButton_3->setGeometry(QRect(430, 110, 20, 20));
        BModiImp = new QPushButton(Modificar);
        BModiImp->setObjectName(QString::fromUtf8("BModiImp"));
        BModiImp->setGeometry(QRect(220, 230, 93, 28));
        BModiCan = new QPushButton(Modificar);
        BModiCan->setObjectName(QString::fromUtf8("BModiCan"));
        BModiCan->setGeometry(QRect(220, 190, 93, 28));
        BModVol = new QPushButton(Modificar);
        BModVol->setObjectName(QString::fromUtf8("BModVol"));
        BModVol->setGeometry(QRect(360, 190, 93, 28));
        BModVol_2 = new QPushButton(Modificar);
        BModVol_2->setObjectName(QString::fromUtf8("BModVol_2"));
        BModVol_2->setGeometry(QRect(360, 230, 93, 28));
        tabAdm->addTab(Modificar, QString());
        tab_9 = new QWidget();
        tab_9->setObjectName(QString::fromUtf8("tab_9"));
        LConsultar = new QLabel(tab_9);
        LConsultar->setObjectName(QString::fromUtf8("LConsultar"));
        LConsultar->setGeometry(QRect(110, 20, 351, 41));
        LTipoCon = new QLabel(tab_9);
        LTipoCon->setObjectName(QString::fromUtf8("LTipoCon"));
        LTipoCon->setGeometry(QRect(50, 120, 55, 16));
        CBTipoCon = new QComboBox(tab_9);
        CBTipoCon->setObjectName(QString::fromUtf8("CBTipoCon"));
        CBTipoCon->setGeometry(QRect(140, 120, 201, 22));
        BBuscarPrecioCon = new QPushButton(tab_9);
        BBuscarPrecioCon->setObjectName(QString::fromUtf8("BBuscarPrecioCon"));
        BBuscarPrecioCon->setGeometry(QRect(170, 170, 121, 31));
        BBuscarOtraCon = new QPushButton(tab_9);
        BBuscarOtraCon->setObjectName(QString::fromUtf8("BBuscarOtraCon"));
        BBuscarOtraCon->setGeometry(QRect(430, 190, 121, 31));
        LCDPrecioCon = new QLCDNumber(tab_9);
        LCDPrecioCon->setObjectName(QString::fromUtf8("LCDPrecioCon"));
        LCDPrecioCon->setGeometry(QRect(400, 110, 151, 71));
        BPrecioCon = new QPushButton(tab_9);
        BPrecioCon->setObjectName(QString::fromUtf8("BPrecioCon"));
        BPrecioCon->setGeometry(QRect(170, 70, 241, 31));
        BImpCon = new QPushButton(tab_9);
        BImpCon->setObjectName(QString::fromUtf8("BImpCon"));
        BImpCon->setGeometry(QRect(170, 140, 241, 31));
        BCanCon = new QPushButton(tab_9);
        BCanCon->setObjectName(QString::fromUtf8("BCanCon"));
        BCanCon->setGeometry(QRect(170, 210, 241, 31));
        BBuscarProdCon = new QPushButton(tab_9);
        BBuscarProdCon->setObjectName(QString::fromUtf8("BBuscarProdCon"));
        BBuscarProdCon->setGeometry(QRect(170, 170, 121, 31));
        BBuscarPasilloCon = new QPushButton(tab_9);
        BBuscarPasilloCon->setObjectName(QString::fromUtf8("BBuscarPasilloCon"));
        BBuscarPasilloCon->setGeometry(QRect(150, 170, 121, 31));
        LColonIma = new QLabel(tab_9);
        LColonIma->setObjectName(QString::fromUtf8("LColonIma"));
        LColonIma->setGeometry(QRect(350, 120, 81, 61));
        porcentaje = new QLabel(tab_9);
        porcentaje->setObjectName(QString::fromUtf8("porcentaje"));
        porcentaje->setGeometry(QRect(560, 110, 61, 61));
        confirmacion_2 = new QLabel(tab_9);
        confirmacion_2->setObjectName(QString::fromUtf8("confirmacion_2"));
        confirmacion_2->setGeometry(QRect(440, 60, 151, 121));
        confirmacion_3 = new QLabel(tab_9);
        confirmacion_3->setObjectName(QString::fromUtf8("confirmacion_3"));
        confirmacion_3->setGeometry(QRect(450, 70, 151, 121));
        confirmacion_4 = new QLabel(tab_9);
        confirmacion_4->setObjectName(QString::fromUtf8("confirmacion_4"));
        confirmacion_4->setGeometry(QRect(460, 60, 151, 121));
        tabAdm->addTab(tab_9, QString());
        tab_11 = new QWidget();
        tab_11->setObjectName(QString::fromUtf8("tab_11"));
        label = new QLabel(tab_11);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(130, 20, 371, 16));
        LPasEl = new QLabel(tab_11);
        LPasEl->setObjectName(QString::fromUtf8("LPasEl"));
        LPasEl->setGeometry(QRect(130, 70, 55, 16));
        LMarEl = new QLabel(tab_11);
        LMarEl->setObjectName(QString::fromUtf8("LMarEl"));
        LMarEl->setGeometry(QRect(130, 150, 55, 16));
        LProdEl = new QLabel(tab_11);
        LProdEl->setObjectName(QString::fromUtf8("LProdEl"));
        LProdEl->setGeometry(QRect(130, 110, 55, 16));
        BElimarPas = new QPushButton(tab_11);
        BElimarPas->setObjectName(QString::fromUtf8("BElimarPas"));
        BElimarPas->setGeometry(QRect(160, 180, 93, 28));
        BPasilloEl = new QPushButton(tab_11);
        BPasilloEl->setObjectName(QString::fromUtf8("BPasilloEl"));
        BPasilloEl->setGeometry(QRect(200, 50, 221, 31));
        BProdEl = new QPushButton(tab_11);
        BProdEl->setObjectName(QString::fromUtf8("BProdEl"));
        BProdEl->setGeometry(QRect(200, 110, 221, 31));
        BMarcaEl = new QPushButton(tab_11);
        BMarcaEl->setObjectName(QString::fromUtf8("BMarcaEl"));
        BMarcaEl->setGeometry(QRect(200, 170, 221, 31));
        CBPasEl = new QComboBox(tab_11);
        CBPasEl->setObjectName(QString::fromUtf8("CBPasEl"));
        CBPasEl->setGeometry(QRect(220, 70, 181, 22));
        CBProdEl = new QComboBox(tab_11);
        CBProdEl->setObjectName(QString::fromUtf8("CBProdEl"));
        CBProdEl->setGeometry(QRect(220, 110, 181, 22));
        CBMarEl = new QComboBox(tab_11);
        CBMarEl->setObjectName(QString::fromUtf8("CBMarEl"));
        CBMarEl->setGeometry(QRect(220, 160, 181, 22));
        BEliminaProd = new QPushButton(tab_11);
        BEliminaProd->setObjectName(QString::fromUtf8("BEliminaProd"));
        BEliminaProd->setGeometry(QRect(160, 150, 93, 28));
        pushButton_4 = new QPushButton(tab_11);
        pushButton_4->setObjectName(QString::fromUtf8("pushButton_4"));
        pushButton_4->setGeometry(QRect(400, 110, 20, 20));
        pushButton_5 = new QPushButton(tab_11);
        pushButton_5->setObjectName(QString::fromUtf8("pushButton_5"));
        pushButton_5->setGeometry(QRect(400, 160, 20, 20));
        BEliminarMarca = new QPushButton(tab_11);
        BEliminarMarca->setObjectName(QString::fromUtf8("BEliminarMarca"));
        BEliminarMarca->setGeometry(QRect(160, 220, 93, 28));
        BClieEl = new QPushButton(tab_11);
        BClieEl->setObjectName(QString::fromUtf8("BClieEl"));
        BClieEl->setGeometry(QRect(200, 230, 221, 31));
        LCED = new QLabel(tab_11);
        LCED->setObjectName(QString::fromUtf8("LCED"));
        LCED->setGeometry(QRect(390, 110, 55, 16));
        TCedEl = new QLineEdit(tab_11);
        TCedEl->setObjectName(QString::fromUtf8("TCedEl"));
        TCedEl->setGeometry(QRect(440, 110, 161, 22));
        BBusEl = new QPushButton(tab_11);
        BBusEl->setObjectName(QString::fromUtf8("BBusEl"));
        BBusEl->setGeometry(QRect(460, 150, 93, 28));
        BSel = new QPushButton(tab_11);
        BSel->setObjectName(QString::fromUtf8("BSel"));
        BSel->setGeometry(QRect(80, 200, 93, 28));
        BActCB = new QPushButton(tab_11);
        BActCB->setObjectName(QString::fromUtf8("BActCB"));
        BActCB->setGeometry(QRect(270, 180, 93, 28));
        BActProd = new QPushButton(tab_11);
        BActProd->setObjectName(QString::fromUtf8("BActProd"));
        BActProd->setGeometry(QRect(270, 150, 93, 28));
        BActMarProd = new QPushButton(tab_11);
        BActMarProd->setObjectName(QString::fromUtf8("BActMarProd"));
        BActMarProd->setGeometry(QRect(270, 220, 93, 28));
        LQClientes = new QListWidget(tab_11);
        LQClientes->setObjectName(QString::fromUtf8("LQClientes"));
        LQClientes->setGeometry(QRect(30, 40, 351, 151));
        BVolver = new QPushButton(tab_11);
        BVolver->setObjectName(QString::fromUtf8("BVolver"));
        BVolver->setGeometry(QRect(390, 150, 93, 28));
        BVolver_2 = new QPushButton(tab_11);
        BVolver_2->setObjectName(QString::fromUtf8("BVolver_2"));
        BVolver_2->setGeometry(QRect(390, 220, 93, 28));
        BVolver_3 = new QPushButton(tab_11);
        BVolver_3->setObjectName(QString::fromUtf8("BVolver_3"));
        BVolver_3->setGeometry(QRect(390, 180, 93, 28));
        BVolver_4 = new QPushButton(tab_11);
        BVolver_4->setObjectName(QString::fromUtf8("BVolver_4"));
        BVolver_4->setGeometry(QRect(200, 200, 93, 28));
        tabAdm->addTab(tab_11, QString());
        tab_12 = new QWidget();
        tab_12->setObjectName(QString::fromUtf8("tab_12"));
        BGondolas = new QPushButton(tab_12);
        BGondolas->setObjectName(QString::fromUtf8("BGondolas"));
        BGondolas->setGeometry(QRect(210, 70, 181, 71));
        BInven = new QPushButton(tab_12);
        BInven->setObjectName(QString::fromUtf8("BInven"));
        BInven->setGeometry(QRect(220, 180, 181, 71));
        LVeri = new QLabel(tab_12);
        LVeri->setObjectName(QString::fromUtf8("LVeri"));
        LVeri->setGeometry(QRect(90, 0, 481, 61));
        LQGong = new QListWidget(tab_12);
        LQGong->setObjectName(QString::fromUtf8("LQGong"));
        LQGong->setGeometry(QRect(20, 50, 256, 192));
        BAgregar = new QPushButton(tab_12);
        BAgregar->setObjectName(QString::fromUtf8("BAgregar"));
        BAgregar->setGeometry(QRect(340, 130, 111, 28));
        LCantGon = new QLabel(tab_12);
        LCantGon->setObjectName(QString::fromUtf8("LCantGon"));
        LCantGon->setGeometry(QRect(290, 80, 111, 16));
        BVolverGon = new QPushButton(tab_12);
        BVolverGon->setObjectName(QString::fromUtf8("BVolverGon"));
        BVolverGon->setGeometry(QRect(470, 130, 111, 28));
        SGon = new QSpinBox(tab_12);
        SGon->setObjectName(QString::fromUtf8("SGon"));
        SGon->setGeometry(QRect(410, 80, 141, 22));
        LQInv = new QListWidget(tab_12);
        LQInv->setObjectName(QString::fromUtf8("LQInv"));
        LQInv->setGeometry(QRect(20, 50, 256, 192));
        BVolverInv = new QPushButton(tab_12);
        BVolverInv->setObjectName(QString::fromUtf8("BVolverInv"));
        BVolverInv->setGeometry(QRect(470, 130, 111, 28));
        BAgregarInv = new QPushButton(tab_12);
        BAgregarInv->setObjectName(QString::fromUtf8("BAgregarInv"));
        BAgregarInv->setGeometry(QRect(340, 130, 111, 28));
        sInv = new QSpinBox(tab_12);
        sInv->setObjectName(QString::fromUtf8("sInv"));
        sInv->setGeometry(QRect(410, 80, 141, 22));
        tabAdm->addTab(tab_12, QString());
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        CBRPas1 = new QComboBox(tab);
        CBRPas1->setObjectName(QString::fromUtf8("CBRPas1"));
        CBRPas1->setGeometry(QRect(30, 60, 311, 22));
        CBRPas2 = new QComboBox(tab);
        CBRPas2->setObjectName(QString::fromUtf8("CBRPas2"));
        CBRPas2->setGeometry(QRect(30, 120, 311, 22));
        CBRPro1 = new QComboBox(tab);
        CBRPro1->setObjectName(QString::fromUtf8("CBRPro1"));
        CBRPro1->setGeometry(QRect(360, 180, 221, 22));
        CBRPas3 = new QComboBox(tab);
        CBRPas3->setObjectName(QString::fromUtf8("CBRPas3"));
        CBRPas3->setGeometry(QRect(10, 180, 221, 22));
        CBRPas4 = new QComboBox(tab);
        CBRPas4->setObjectName(QString::fromUtf8("CBRPas4"));
        CBRPas4->setGeometry(QRect(10, 240, 221, 22));
        CBRPro2 = new QComboBox(tab);
        CBRPro2->setObjectName(QString::fromUtf8("CBRPro2"));
        CBRPro2->setGeometry(QRect(360, 240, 221, 22));
        label_2 = new QLabel(tab);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(50, 90, 291, 16));
        label_3 = new QLabel(tab);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(80, 30, 291, 16));
        label_4 = new QLabel(tab);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(160, 210, 291, 16));
        label_5 = new QLabel(tab);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(180, 150, 291, 16));
        pushButton_6 = new QPushButton(tab);
        pushButton_6->setObjectName(QString::fromUtf8("pushButton_6"));
        pushButton_6->setGeometry(QRect(420, 70, 151, 41));
        BBRPas4 = new QPushButton(tab);
        BBRPas4->setObjectName(QString::fromUtf8("BBRPas4"));
        BBRPas4->setGeometry(QRect(250, 240, 20, 20));
        BBRPas3 = new QPushButton(tab);
        BBRPas3->setObjectName(QString::fromUtf8("BBRPas3"));
        BBRPas3->setGeometry(QRect(250, 180, 20, 20));
        BBRPas1 = new QPushButton(tab);
        BBRPas1->setObjectName(QString::fromUtf8("BBRPas1"));
        BBRPas1->setGeometry(QRect(350, 60, 20, 20));
        BBRPas2 = new QPushButton(tab);
        BBRPas2->setObjectName(QString::fromUtf8("BBRPas2"));
        BBRPas2->setGeometry(QRect(350, 120, 20, 20));
        BBRPro2 = new QPushButton(tab);
        BBRPro2->setObjectName(QString::fromUtf8("BBRPro2"));
        BBRPro2->setGeometry(QRect(590, 240, 20, 20));
        BBRPro1 = new QPushButton(tab);
        BBRPro1->setObjectName(QString::fromUtf8("BBRPro1"));
        BBRPro1->setGeometry(QRect(590, 180, 20, 20));
        tabAdm->addTab(tab, QString());
        tab_13 = new QWidget();
        tab_13->setObjectName(QString::fromUtf8("tab_13"));
        BFacturar = new QPushButton(tab_13);
        BFacturar->setObjectName(QString::fromUtf8("BFacturar"));
        BFacturar->setGeometry(QRect(200, 80, 231, 51));
        LOtros = new QLabel(tab_13);
        LOtros->setObjectName(QString::fromUtf8("LOtros"));
        LOtros->setGeometry(QRect(220, 20, 201, 31));
        pushButton_7 = new QPushButton(tab_13);
        pushButton_7->setObjectName(QString::fromUtf8("pushButton_7"));
        pushButton_7->setGeometry(QRect(30, 190, 121, 31));
        pushButton_8 = new QPushButton(tab_13);
        pushButton_8->setObjectName(QString::fromUtf8("pushButton_8"));
        pushButton_8->setGeometry(QRect(190, 190, 121, 31));
        pushButton_9 = new QPushButton(tab_13);
        pushButton_9->setObjectName(QString::fromUtf8("pushButton_9"));
        pushButton_9->setGeometry(QRect(340, 190, 121, 31));
        pushButton_10 = new QPushButton(tab_13);
        pushButton_10->setObjectName(QString::fromUtf8("pushButton_10"));
        pushButton_10->setGeometry(QRect(490, 190, 121, 31));
        tabAdm->addTab(tab_13, QString());
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 634, 20));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        tabAdm->setCurrentIndex(5);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        LBienve->setText(QApplication::translate("MainWindow", "Bienvenido al supermercado", nullptr));
        LCodAdm->setText(QApplication::translate("MainWindow", "Codigo de administrador", nullptr));
        LDijite->setText(QApplication::translate("MainWindow", "Dijite su codigo de administrador ", nullptr));
        LInfo->setText(QString());
        BIngresar_3->setText(QApplication::translate("MainWindow", "Ingresar", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(tab_7), QApplication::translate("MainWindow", "Ingresar", nullptr));
        LInsertar->setText(QApplication::translate("MainWindow", "Inserte pasillos, productos o marcas nuevas ", nullptr));
        BPasillo->setText(QApplication::translate("MainWindow", "Insertar Pasillo", nullptr));
        BProducto->setText(QApplication::translate("MainWindow", "Insertar Producto", nullptr));
        BMarca->setText(QApplication::translate("MainWindow", "Insertar Marca", nullptr));
        LTipo->setText(QString());
        BinsertarPas->setText(QApplication::translate("MainWindow", "Insertar", nullptr));
        LNombre->setText(QApplication::translate("MainWindow", "Nombre", nullptr));
        LCodPas->setText(QApplication::translate("MainWindow", "Codigo", nullptr));
        LPasillo->setText(QApplication::translate("MainWindow", "Pasillo", nullptr));
        BInsertarProd->setText(QApplication::translate("MainWindow", "Insertar", nullptr));
        LProducto->setText(QApplication::translate("MainWindow", "Producto", nullptr));
        BInsertarMarca->setText(QApplication::translate("MainWindow", "Insertar", nullptr));
        pushButton->setText(QString());
        LNombreM->setText(QApplication::translate("MainWindow", "Nombre", nullptr));
        LCodMar->setText(QApplication::translate("MainWindow", "Codigo", nullptr));
        LPasilloM->setText(QApplication::translate("MainWindow", "Pasillo", nullptr));
        LCantidad->setText(QApplication::translate("MainWindow", "Cantidad", nullptr));
        LPrecio->setText(QApplication::translate("MainWindow", "Precio", nullptr));
        LCanasta->setText(QApplication::translate("MainWindow", "Canasta ", nullptr));
        RBS->setText(QApplication::translate("MainWindow", "S\303\255", nullptr));
        RBN->setText(QApplication::translate("MainWindow", "NO", nullptr));
        BVolver3->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolver2->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolver1->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(tab_8), QApplication::translate("MainWindow", "Insertar", nullptr));
        BModPrecio->setText(QApplication::translate("MainWindow", "Precio", nullptr));
        LModificar->setText(QApplication::translate("MainWindow", "Modifique el precio, el impuesto o la canasta de las marcas del supermercado", nullptr));
        BModImp->setText(QApplication::translate("MainWindow", "Impuesto", nullptr));
        BModCan->setText(QApplication::translate("MainWindow", "Canasta ", nullptr));
        LPasMod->setText(QApplication::translate("MainWindow", "Pasillo", nullptr));
        LProdMod->setText(QApplication::translate("MainWindow", "Producto", nullptr));
        LMarMod->setText(QApplication::translate("MainWindow", "Marca", nullptr));
        BModi->setText(QApplication::translate("MainWindow", "Moificar", nullptr));
        LMod->setText(QApplication::translate("MainWindow", "Precio", nullptr));
        pushButton_2->setText(QString());
        pushButton_3->setText(QString());
        BModiImp->setText(QApplication::translate("MainWindow", "Moificar", nullptr));
        BModiCan->setText(QApplication::translate("MainWindow", "Moificar", nullptr));
        BModVol->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BModVol_2->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(Modificar), QApplication::translate("MainWindow", "Modificar", nullptr));
        LConsultar->setText(QApplication::translate("MainWindow", "Consulte el precio, el impuesto o la canasta de un producto", nullptr));
        LTipoCon->setText(QApplication::translate("MainWindow", "Pasillos", nullptr));
        BBuscarPrecioCon->setText(QApplication::translate("MainWindow", "Buscar Marca", nullptr));
        BBuscarOtraCon->setText(QApplication::translate("MainWindow", "Buscar otra marca", nullptr));
        BPrecioCon->setText(QApplication::translate("MainWindow", "Precio", nullptr));
        BImpCon->setText(QApplication::translate("MainWindow", "Impuesto", nullptr));
        BCanCon->setText(QApplication::translate("MainWindow", "Canasta", nullptr));
        BBuscarProdCon->setText(QApplication::translate("MainWindow", "Buscar en producto", nullptr));
        BBuscarPasilloCon->setText(QApplication::translate("MainWindow", "Buscar en pasillo", nullptr));
        LColonIma->setText(QString());
        porcentaje->setText(QString());
        confirmacion_2->setText(QString());
        confirmacion_3->setText(QString());
        confirmacion_4->setText(QString());
        tabAdm->setTabText(tabAdm->indexOf(tab_9), QApplication::translate("MainWindow", "Consultar", nullptr));
        label->setText(QApplication::translate("MainWindow", "Elimine pasillos, productos, marcas y clientes del supermercado", nullptr));
        LPasEl->setText(QApplication::translate("MainWindow", "Pasillo", nullptr));
        LMarEl->setText(QApplication::translate("MainWindow", "Marca", nullptr));
        LProdEl->setText(QApplication::translate("MainWindow", "Producto", nullptr));
        BElimarPas->setText(QApplication::translate("MainWindow", "Eliminar", nullptr));
        BPasilloEl->setText(QApplication::translate("MainWindow", "Pasillo", nullptr));
        BProdEl->setText(QApplication::translate("MainWindow", "Producto", nullptr));
        BMarcaEl->setText(QApplication::translate("MainWindow", "Marca", nullptr));
        BEliminaProd->setText(QApplication::translate("MainWindow", "Eliminar", nullptr));
        pushButton_4->setText(QString());
        pushButton_5->setText(QString());
        BEliminarMarca->setText(QApplication::translate("MainWindow", "Eliminar", nullptr));
        BClieEl->setText(QApplication::translate("MainWindow", "Cliente", nullptr));
        LCED->setText(QApplication::translate("MainWindow", "Cedula", nullptr));
        BBusEl->setText(QApplication::translate("MainWindow", "Buscar", nullptr));
        BSel->setText(QApplication::translate("MainWindow", "Seleccionar ", nullptr));
        BActCB->setText(QApplication::translate("MainWindow", "Actualizar", nullptr));
        BActProd->setText(QApplication::translate("MainWindow", "Actualizar", nullptr));
        BActMarProd->setText(QApplication::translate("MainWindow", "Actualizar", nullptr));
        BVolver->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolver_2->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolver_3->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolver_4->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(tab_11), QApplication::translate("MainWindow", "Eliminar", nullptr));
        BGondolas->setText(QApplication::translate("MainWindow", "Gondolas", nullptr));
        BInven->setText(QApplication::translate("MainWindow", "Inventario", nullptr));
        LVeri->setText(QApplication::translate("MainWindow", "Verifique la cantidad de productos que hay en las gondolas y en el inventario", nullptr));
        BAgregar->setText(QApplication::translate("MainWindow", "Agregar Cantidad", nullptr));
        LCantGon->setText(QApplication::translate("MainWindow", "Cantidad a rellenar", nullptr));
        BVolverGon->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BVolverInv->setText(QApplication::translate("MainWindow", "Volver", nullptr));
        BAgregarInv->setText(QApplication::translate("MainWindow", "Agregar Cantidad", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(tab_12), QApplication::translate("MainWindow", "Verificar", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Seleccione para ver el Producto mas vendido del pasillo", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Seleccione para ver los Productos del pasillo", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Seleccione para ver Marca mas vendida del Producto", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Seleccione para ver las Marcas del Producto", nullptr));
        pushButton_6->setText(QApplication::translate("MainWindow", "Generar Reporte", nullptr));
        BBRPas4->setText(QString());
        BBRPas3->setText(QString());
        BBRPas1->setText(QString());
        BBRPas2->setText(QString());
        BBRPro2->setText(QString());
        BBRPro1->setText(QString());
        tabAdm->setTabText(tabAdm->indexOf(tab), QApplication::translate("MainWindow", "Reportes", nullptr));
        BFacturar->setText(QApplication::translate("MainWindow", "Facturar", nullptr));
        LOtros->setText(QApplication::translate("MainWindow", "Otras funcionalidades disponibles", nullptr));
        pushButton_7->setText(QApplication::translate("MainWindow", "Entrega de Compras", nullptr));
        pushButton_8->setText(QApplication::translate("MainWindow", "Ruta hacia la bodega", nullptr));
        pushButton_9->setText(QApplication::translate("MainWindow", "Puntos de Articulacion", nullptr));
        pushButton_10->setText(QApplication::translate("MainWindow", "Ver mapa", nullptr));
        tabAdm->setTabText(tabAdm->indexOf(tab_13), QApplication::translate("MainWindow", "Otros", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
